# Site settings
title: NeCTAR National Training
email: no-reply@intersect.org.au
description: > # this means to ignore newlines until "baseurl:"
  NeCTAR National Training Resources
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
